server:
  port: 8070
  use-forward-headers: false
  servlet:
    context-path: /uaa
 
spring:
  profiles: default
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    platform: psql
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update  
    
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

# Ribbon config
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

