spring:
  application:
    name: api-gateway
  profiles: default
    
server:
  port: 8765

#Zuul config    
zuul:
  ignoredServices: "*"
  routes:
    auth-server:  
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
      serviceId: auth-server
    user-service:  
      sensitiveHeaders:
      path: /user/**
      serviceId: user-service
    task1-service:  
      sensitiveHeaders:
      path: /task1/**
      serviceId: task1-service
   
  ignored-headers:
    - Access-Control-Allow-Credentials
    - Access-Control-Allow-Origin      
#Eureka config  
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


# Ribbon config
ribbon: 
  ConnectTimeout: 3000
  ReadTimeout: 9900
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
